name: federate test

on:
  push:
    branches:
    - '*'

jobs:
  auth:
    permissions:
      contents: 'read'
      id-token: 'write'

    uses: menulpatrol/workflows/.github/workflows/shared.yaml@master
    with:
      echo: Bla
